### ISSUE TITLE
La concha de tu madre pato

### ISSUE THREAD

**Issue by reynico** [alcuadrado/pija#2]
python2 pija Bic+1.jpg 
Traceback (most recent call last):
  File "pija", line 55, in <module>
    print_result(file_, analize(file_))
  File "/home/nico/pija/analizer.py", line 57, in analize
    type_ = magic.from_file(path)
AttributeError: 'module' object has no attribute 'from_file'

**Comment by mattaereal** [comment]
This has been already solved with requirements.txt
